/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-17 at 20:17:59 UTC 
 * Modify at your own risk.
 */

package none.carpooling.model;

import java.io.Serializable;

/**
 * ProtoRPC container for GeoPt instances. Attributes: lat: Float; The latitude of the point. lon:
 * Float; The longitude of the point.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the carpooling. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GeoPtMessage extends com.google.api.client.json.GenericJson implements Serializable {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Double lat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Double lon;

  /**
   * @return value or {@code null} for none
   */
  public Double getLat() {
    return lat;
  }

  /**
   * @param lat lat or {@code null} for none
   */
  public GeoPtMessage setLat(Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Double getLon() {
    return lon;
  }

  /**
   * @param lon lon or {@code null} for none
   */
  public GeoPtMessage setLon(Double lon) {
    this.lon = lon;
    return this;
  }

  @Override
  public GeoPtMessage set(String fieldName, Object value) {
    return (GeoPtMessage) super.set(fieldName, value);
  }

  @Override
  public GeoPtMessage clone() {
    return (GeoPtMessage) super.clone();
  }

}
