/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-17 at 20:17:59 UTC 
 * Modify at your own risk.
 */

package none.carpooling.model;

/**
 * Model definition for RunRequestCollection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the carpooling. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RunRequestCollection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<RunRequest> items;

  static {
    // hack to force ProGuard to consider RunRequest used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(RunRequest.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String nextPageToken;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<RunRequest> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public RunRequestCollection setItems(java.util.List<RunRequest> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getNextPageToken() {
    return nextPageToken;
  }

  /**
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  public RunRequestCollection setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public RunRequestCollection set(String fieldName, Object value) {
    return (RunRequestCollection) super.set(fieldName, value);
  }

  @Override
  public RunRequestCollection clone() {
    return (RunRequestCollection) super.clone();
  }

}
